### ISSUE TITLE
api.globalbioticinteractions.org/taxon endpoint not working

### ISSUE THREAD

**Issue by drgirasol** [globalbioticinteractions/globalbioticinteractions#697] opened 2021-09-14 07:25 UTC
Any request to api.globalbioticinteractions.org/taxon endpoint resulting in 
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Also not working (same error): 
https://api.globalbioticinteractions.org/interaction?targetTaxon=Callinectes%20sapidus&limit=5

**Comment by jhpoelen** [comment] 2021-09-14 09:07
@drgirasol Thanks for sharing and apologies for the inconvenience. I am looking into it as we speak.

**Comment by jhpoelen** [comment] 2021-09-14 09:21
I've determined the root cause and reverted to an earlier version of the GloBI API . 

Please note that now results are returned as expected: 

```
$ curl --silent "https://api.globalbioticinteractions.org/interaction?targetTaxon=Callinectes%20sapidus&limit=5" | jq . | head
{
  "columns": [
    "source_taxon_external_id",
    "source_taxon_name",
    "source_taxon_path",
    "source_specimen_occurrence_id",
    "source_specimen_institution_code",
    "source_specimen_collection_code",
    "source_specimen_catalog_number",
    "source_specimen_life_stage",
...
```
Also, see attached screenshot. 
![Screenshot from 2021-09-14 02-20-53](https://user-images.githubusercontent.com/1084872/133231556-083093b0-0544-4a0a-9c1f-a8c9dbe1befb.png)

**Comment by jhpoelen** [comment] 2021-09-14 09:24
The root cause was an incompatible version of the GloBI API and their current underlying graph database neo4j. I've reverted to an older version as I am preparing for a (hopefully) successful upgrade of both the GloBI API and associated neo4j database. 

Please confirm that your reported issue has been resolved by closing this issue. 

Also, thanks for being patient in reporting this issue.

**Comment by jhpoelen** [comment] 2021-09-14 11:09
In digging deeper into the root cause, I found that the upgrade of lucene to v5.5.5 as part of the neo4j v3.4.* introduced a mandatory quoting of white spaces in queries:

see https://stackoverflow.com/questions/17798300/lucene-queryparser-with-in-query-criteria
see https://lucene.apache.org/core/4_0_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Regexp_Searches 

with related GloBI API change - 
https://github.com/globalbioticinteractions/globalbioticinteractions/commit/dd35672b92a61736d1a487f6e8d368fb23e3b909

**Closed** 2021-09-14 14:11 UTC
Labels: bug, needs data review
