### ISSUE TITLE
API appears to be down

### ISSUE THREAD

**Issue by chili-b** [globalbioticinteractions/globalbioticinteractions#651] opened 2021-04-13 17:06 UTC
Sorry if this is just something on my end, but I can't query the API with anything right now, I just get an error.

**Comment by jhpoelen** [comment] 2021-04-13 18:02
hi @chili-b - thanks for your message! How are you using the API? What specific queries are you using? If you provide detailed information, we can hopefully figure out what is going on.

**Comment by jhpoelen** [comment] 2021-04-13 18:16
@chili-b I was able to reproduce an issue with GloBI's search index. Working on a fix as we speak. Thanks for being patient.

**Comment by jhpoelen** [comment] 2021-04-13 18:33
@chili-b I was able to restore a corrupted version of GloBI's search index. The reason for the corruption was . . . a (silly) out of disk space issue. I have monitors in place to automatically check on the health of GloBI, but apparently improvements are needed. I've opened a separate issue on that at https://github.com/globalbioticinteractions/globalbioticinteractions/issues/652 .

The issue started at 18:05 CEST today and was resolved 20:35 CEST (two and a half hours later). My apologies for the interruption and am open to ideas to prevent this in the future. 

Please do note, that all data products (including the neo4j search index) are available via Zenodo (released versions) and GloBI's depot (snapshot version) via https://globalbioticinteractions.org/data . These products are available even if GloBI's hosted index is not.

I'll close this issue and please feel free to re-open if you feel the issue has not been resolved.

**Closed by jhpoelen** 2021-04-13 18:33 UTC

**Comment by chili-b** [comment] 2021-04-13 19:11
It's working for me. Thanks for the quick response!
