### ISSUE TITLE
Refute interacton

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#552] opened 2020-10-30 17:06 UTC
![Screen Shot 2020-10-30 at 10 04 22 AM](https://user-images.githubusercontent.com/1044474/97735369-7a597900-1a97-11eb-8115-2488e9119974.png)

Bee is not parasite of mite, mite parasite of bee

**Comment by jhpoelen** [comment] 2020-10-30 20:10
Thanks! Instead of using common names, could you express your refutation rule using taxonomic names / hierarchies?

**Comment by seltmann** [comment] 2020-10-30 20:44
Ceratina is not a parasite of Chaetodactylus leleupi

**Comment by jhpoelen** [comment] 2020-10-30 22:42
@seltmann thanks! I recorded your refutation in a general purpose refutation dataset at https://github.com/globalbioticinteractions/refuted-interaction-data . Please feel free to add to this in the future, or . . . create your own! 

Please inspect the added refutation record at https://github.com/globalbioticinteractions/refuted-interaction-data/commit/46b694bedc14e0015aa11aa7c5f18cfb9cfc01fb . If you like the result, please close this issue. Otherwise, please holler suggestions / ideas to better address this.

**Comment by jhpoelen** [comment] 2020-11-03 15:23
@seltmann I was reviewing the refutation records and noticed that the label "has parasite" for the refuted claim "Ceratina parasite of _Chaetodactylus leleupi_" did not match with provided RO term http://purl.obolibrary.org/obo/RO_0002445 .

I've corrected my mistake and applied the interaction type URI http://purl.obolibrary.org/obo/RO_0002444 instead. The root cause was a copy/paste error from previous record, where the label was incorrect, but the RO term was correct.

I need an interaction spell checker! Wanna build one?

PS Also, I was wondering whether you'd be comfortable generalizing refutations of any claim that involves bees parasitizing mites. If so, please share your claims and I can record them.

**Comment by seltmann** [comment] 2020-11-04 20:41
@jhpoelen An interaction spell checker, so interacts with, intaracts with (=interacts with)? I would be good at this because I am one of the worst spellers!

Yes, I would be comfortable generalizing refutations of any claim that involves bees parasitizing mites.

**Comment by jhpoelen** [comment] 2020-11-09 18:21
hey @seltmann - your refutation record now shows up as expected. Also note that there's no supporting claim for your refuted interaction because of recent improvements made via #553 . Also, please feel free to add more refutation statement to https://github.com/globalbioticinteractions/refuted-interaction-data or a refutation dataset of your own.  See attached screenshot for the refuted interaction as seen via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Frefuted-interaction-data&interactionType=interactsWith&sourceTaxon=Ceratina

![Screenshot from 2020-11-09 10-21-07](https://user-images.githubusercontent.com/1084872/98580720-4e977980-2275-11eb-9eb9-dc8a56ab814c.png)
 . 

Please comment and/or re-open if the issue has not yet been resolved.

**Closed by jhpoelen** 2020-11-09 18:21 UTC
