### ISSUE TITLE
The text ```Severe acute respiratory syndrome coronavirus``` links to  ```https://sandbox.zenodo.org/search?custom=%5Bobo%3ARO_0002453%5D%3A%5B%3ASevere+acute+respiratory+syndrome+coronavirus%5D``` which encodes the verb ```[ro:RO_0002453]``` [host of](http://purl.obolibrary.org/obo/RO_0002453)  to  object ```Severe acute respiratory syndrome coronavirus```.  Having the virus be the object of the verb "(is) host of" does make sense, because the sentence "X host of virus Y" makes biological sense.

### ISSUE THREAD

**Issue by Yshatyi122** [globalbioticinteractions/globalbioticinteractions#932] opened 2023-10-31 16:24 UTC
The text ```Severe acute respiratory syndrome coronavirus``` links to  ```https://sandbox.zenodo.org/search?custom=%5Bobo%3ARO_0002453%5D%3A%5B%3ASevere+acute+respiratory+syndrome+coronavirus%5D``` which encodes the verb ```[ro:RO_0002453]``` [host of](http://purl.obolibrary.org/obo/RO_0002453)  to  object ```Severe acute respiratory syndrome coronavirus```.  Having the virus be the object of the verb "(is) host of" does make sense, because the sentence "X host of virus Y" makes biological sense. 

However, the text ```Rhinophus``` links to ```search?custom=%5Bobo%3ARO_0002453%5D%3A%5BRhinolophus%3A%5D]```, which encodes the verb ```[obo:RO_0002453]``` (or host of) and object ```Rhinolophus``` . 

This does not makes (biological) sense, because the ```Rhinolophus``` is expected to be the subject of the verb ```(is) host of```. 

Instead, I'd expect encodings like:

1. ```Rhinolophus``` :  ```obo:RO_0002453 | (is) host of``` (e.g., bat is a host of virus X where bat is the subject)
or 
2. ```obo:RO_0002454 | has host``` :  ```Rhinolophus``` (e.g., virus X has host bat, where bat is the object)

where ```RO_0002454``` (has host) is the inverse of ```RO_0002453``` (host of).

@slint curious to hear your thoughts on how to ensure the directionality of the species interactions can be preserved in the Zenodo meta-data.

_Originally posted by @jhpoelen in https://github.com/globalbioticinteractions/globalbioticinteractions/issues/488#issuecomment-642853378_

**Comment by jhpoelen** [comment] 2023-10-31 16:44
@Yshatyi122 please let me know why you opened this issue. It appears to be a duplicate of #488 .

**Comment by jhpoelen** [comment] 2023-10-31 17:10
@Yshatyi122 happy to re-open if you provide some reason for this apparent duplicate issue.

**Closed by jhpoelen** 2023-10-31 17:10 UTC
