### ISSUE TITLE
Acari image in Globi portal

### ISSUE THREAD

**Issue by campmlc** [globalbioticinteractions/globalbioticinteractions#438] opened 2019-12-18 19:05 UTC
Hello Globi folks, I just searched on relationships for Acari as a parasite of Perognathus flavus. The results all look fine, but the icon for Acari appears to be a catfish, rather than what I would expect to see - a tick or mite arachnid,e.g. https://en.wikipedia.org/wiki/Acari. Can you replace the icon with something more appropriate?

**Comment by jhpoelen** [comment] 2019-12-19 18:12
@campmlc thanks for pointing this out. The unexpected image of the catfish appeared because of the (incorrect) association of the name "Acari" with "https://www.wikidata.org/wiki/Q6406267" in addition to the expected link to "https://www.wikidata.org/wiki/Q19137" 

GloBI uses wikidata to retrieve key images for linked taxa. In this case, the image was helpful to detect the suspicious wiki link. 

Hoping to provide a root cause analysis and fix in the near future. 

PS. If Arctos has a way to provide openly accessibly thumbnail images for taxa, please let me know. I might be able to add Arctos as a taxon image provider. Might be a little more specific compared to wikidata.

**Comment by jhpoelen** [comment] 2020-01-17 17:49
@campmlc I finally got around to removing the suspicious Acari link to Hypostomus alatus in GloBI taxon graph v0.3.20 released today (also see http://doi.org/10.5281/zenodo.3611464 ). The changes should be visible in the couple of days. Thanks again for pointing this out and I'll close the issue when the changes are visible on https://globalbioticinteractions.org .

**Comment by jhpoelen** [comment] 2020-01-21 17:17
Updates have propagated and looks like the Acari image is now associated with some (expected?) peacock mite image via https://www.wikidata.org/wiki/Q19137 . See attached screenshot of https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Acari .

![Screenshot from 2020-01-21 09-11-45](https://user-images.githubusercontent.com/1084872/72826820-68a49480-3c2e-11ea-8ffb-871acd0462e0.png)

Thanks for your patience, and please re-open or comment if issues remain.

PS. According to ITIS (https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=733321#null) , Acari is an invalid name and  Arachnida  (https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=733321#null) should be used instead.

**Closed by jhpoelen** 2020-01-21 17:17 UTC
Labels: bug, needs data review

**Comment by campmlc** [comment] 2020-01-21 17:26
That is great, thanks.
As for taxonomy, it is an unfortunate consequence of how little we know of
living things that there is no single taxonomic authority or consensus.
Acari is still valid in other sources, including WoRMS:
http://www.marinespecies.org/aphia.php?p=taxdetails&id=292684. We will need
to continue to use subclass Acari to distinguish ticks and mites from other
arachnids until some other option becomes available. We don't want to imply
that all arachnids including spiders have become ectoparasitic - I'm sure
that would terrify many people!

**Comment by jhpoelen** [comment] 2020-01-21 17:37
@campmlc Thanks for providing your taxonomic perspective. GloBI tries to link to all taxonomic name perspectives. This is why Acari also links to, among others, http://www.marinespecies.org/aphia.php?p=taxdetails&id=292684 as well as the referenced ITIS taxon id/page. Rather than to forcing some artificial consensus by introducing a single taxonomic backbone, I favor this pluralist taxonomic approach because I think it better reflects how the names are currently used and understood.

**Comment by campmlc** [comment] 2020-01-21 17:43
I agree with the pluralistic approach.
