### ISSUE TITLE
How to get unique Identifiers for taxa

### ISSUE THREAD

**Issue by BarbaraMeulenbelt** [globalbioticinteractions/globalbioticinteractions#826] opened 2022-10-14 12:56 UTC
Dear J.H.Poelen :)

I'm using the Globi dataset for my AI Msc. thesis at the VU. I've tried different approaches to use the data but eventually went with the whole interactions.csv file and I have been busy with inspecting and pre-processing all the data. I wanted to ask if you can help me with something. As all the different taxa and taxonomic levels have different Id's (either EOL, GBIF, INIT etc.) I am struggling with finding one unique id for every different taxa along with their taxonomic levels (orderId, familyId, genusId). I have looked carefully at nomer but I can not see how I can use this with a big datafile, I'm missing some explanation on this. The datafile I have left is about 8GB. I am going to make a regression like model so I need all the same taxa to have the same identifier. If I'd use the Id that is given in the Globi file, the same species could have an EOL id in one interaction and a GBIF id in another. When I would analyse the interactions then, they would not be seen as the same species. My best try now was to only keep rows that have an GBIF id in their 'sourceTaxonIds'/'targetTaxonIds' column and use that GBIF id as their unique Id. The problem then remains that the orderId, familyId, genusId etc. also have different Ids for the same family/order/genus and that I lose some data.
My goal is to have

A file that contains: sourcetaxonId, interaction, targettaxonId.
A file that contains:
1. taxonId, orderId
2. taxonId, familyId
3. taxonId, genusId
I hope you can help me with this! :)

Kind regards,
Barbara Meulenbelt

**Comment by jhpoelen** [comment] 2022-10-14 13:36
@BarbaraMeulenbelt hoi Barbara - fijn on van je te horen en bedankt voor je gedetaileerde beschrijving. (switching to English now. . .)

Thanks for sharing your challenge in great detail. 

Can you add some specific examples of your input along with your desired output? 

e.g., 

input: 
Homo sapiens eats Canis lupus

output:
 ?

**Comment by jhpoelen** [comment] 2022-10-14 13:38
Oh, and just to get familiar with some methods that others have used, you might find something in the following workshop pages:

https://globalbioticinteractions.org/ecm-workshop
https://globalbioticinteractions.org/interaction-data-workshop
https://globalbioticinteractions.org/deadwood2021

Curious to hear whether this is at all helpful.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 11:09
Hi @jhpoelen 

Thanks for the quick reply! 

I'll continue with your example
input:
Homo sapiens eats Canis lupus
Here, we see the name of the taxa, sometimes 'Homo sapiens' will have a EOL code, sometimes a GBIF etc. so what we might see in the data is:

Id                              Name                   Interaction          Id                 Name              SourceTaxonGenusId      TargetTaxonGenusId
EOL:XXX                  Homo sapiens    eats                     EOL:XXX     Canis Lupus   EOL:XXXX                         EOL:XXXX
GBIF:XXX                 Homo sapiens    eats                     GBIF:XXX    Canis Lupus   GBIF:XXXX                        GBIF:XXXX
EOL:XXX                  Homo sapiens    eats                     GBIF:XXX    Canis Lupus   INIT_TAXON:XX                EOL:XXXX
INAT_TAXON:XXX   Homo sapiens    eats                     EOL:XXX     Canis Lupus   EOL:XXXXX                      GBIF:XXXX

Now, this all refers to the same Homo sapiens and the same Canis Lupus, but all have different codes. If I would take the GBIFid as id for this interaction and find other interactions that include Homo sapiens and there Homo Sapiens has a EOL id, then in making my model, they do not refer to the same taxa as they have different codes. Also the order, family and genera 

What I would like to have as output:
Id                Name                   Interaction             Id                 Name             sourceGenusId       targetTaxonGenusId
one code   Homo sapiens     eats                        one code    Canis Lupus  one code                 one code

Every interaction that I will find in my dataset that contains 'Homo sapiens' needs to have the same code, it doesn't matter whether its EOL, GBIF, etc.
What also would be ok is to have a whole string including name, ids etc (like the output of nomer)

I hope this is clear ;)

Kind regards, 
Barbara Meulenbelt



<br class="Apple-interchange-newline">

**Comment by jhpoelen** [comment] 2022-10-17 11:54
@BarbaraMeulenbelt thanks for taking the time to provide a worked out example. I now understand what you'd like to get from GloBI. Actually, this is something I was hoping someone would ask for . . . 

I am thinking to add specific versions of interactions.tsv.gz / interactions.csv.gz each for specific naming authority - 

interactions.csv.gz (raw names)

interactions-itis.csv.gz (aligned with ITIS)

interactions-eol.csv.gz (aligned with EOL)

interactions-gbif.csv.gz (aligned with EOL)

etc.

What do you think about this idea?

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 11:59
Hi Jorrit,

Well I am happy I asked the question you hoped for! That idea is AMAZING!

I am now trying to link the taxonCache.csv file to the interactions.csv for GBIF codes but it would be much more convenient if there would be an interactions-gbif.csv.gz file!

Is this idea something that could come online in the short-term or will it take a while for you to preparate these files?

Kind regards, 
Barbara

**Comment by jhpoelen** [comment] 2022-10-17 12:04
@BarbaraMeulenbelt when would you need it?

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 12:08
@jhpoelen I have been busy with the dataset a few months and would like to be able to start analysing as soon as possible. So the quicker the better. But do not worry if you need some time to preperate the datasets, I am already really happy that it is an option for these datasets to come online! What is your estimation?

**Comment by jhpoelen** [comment] 2022-10-17 12:11
I'd have to do a little extra scripting, but, I don't expect too much of an issue. 

Just curious - what are the tools that you use for your analysis? what is your programming skill level? 

Trying to figure out how to get the data to you as quickly as I can.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 12:28
Nice! I am going to do a network analysis, using GPFL, (Graph Path Feature Learning) a probabilistic logical rule learner optimized to mine instantiated rules that contain constants from knowledge graphs.

The input for this is RDF triple files so in the end, my data look like:

taxon     interaction     taxon    (for all the interactions)
taxon     is_of_order    order    (for all taxa)
taxon     is_of_family   family   (for all taxa)
taxon     is_of_genus   genus   (for all taxa)

Important is that all the codes are unique, because if different taxa, or taxonomic levels have the same code, GPFL will connect these together like they are the same and this will bias the learned rules 

My programming skills are moderate.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 12:34
I'm currently doing everything in python, on my macbook. I have some experience with bash/commandline but not much.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 12:41
Cool that you are attending TDWG 2022, hope it is informative! For my analysis I want to use the whole dataset. What do you mean with a small dataset? a subset of the whole set?

**Comment by jhpoelen** [comment] 2022-10-17 12:46
@BarbaraMeulenbelt just a small subset to get started before proceeding to the full dataset.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-17 12:56
@jhpoelen Ok!

**Comment by jhpoelen** [comment] 2022-10-18 01:27
@BarbaraMeulenbelt here's some a quick and dirty way to compile your data using https://github.com/globalbioticinteractions/nomer , miller (mlr) https://github.com/johnkerl/miller and commandline tools like gunzip, grep and cut. 

```
curl "https://depot.globalbioticinteractions.org/snapshot/target/data/csv/interactions.csv.gz" | gunzip | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName | nomer replace col | nomer replace --properties replace-target.properties col | grep "COL:.*COL:.*" > id-name-interaction-id-name.tsv
```

with replace-target.properties being: 

```
nomer.schema.input=[{"column":3,"type":"externalId"},{"column": 4,"type":"name"}]
nomer.schema.output=[{"column":3,"type":"externalId"},{"column": 4,"type":"name"}]
```

First 10 records would look something like:

sourceTaxonId | sourceTaxonName | interactionTypeName | targetTaxonId | targetTaxonName 
 --- | --- | --- | --- | --- |
| COL:32YT6 | Cyclura lewisi | eats | COL:78K6T | Psychotria nervosa |
| COL:32YT6 | Cyclura lewisi | eats | COL:4H37G | Phyllanthus amarus |
| COL:32YT6 | Cyclura lewisi | eats | COL:6L5SC | Guapira discolor |
| COL:32YT6 | Cyclura lewisi | eats | COL:3BG33 | Erythroxylum rotundifolium |
| COL:32YT6 | Cyclura lewisi | eats | COL:4NXSD | Pseudogynoxys chenopodioides |
| COL:32YT6 | Cyclura lewisi | eats | COL:3GJKZ | Gmelina philippensis |
| COL:32YT6 | Cyclura lewisi | eats | COL:386LY | Dypsis lastelliana |
| COL:32YT6 | Cyclura lewisi | eats | COL:3538H | Desmodium incanum |

Then, you can associate the genus, family, order with something like:

```
curl "https://depot.globalbioticinteractions.org/snapshot/target/data/csv/interactions.csv.gz"\
 | gunzip\
 | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName\
 | nomer replace col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"\
 | cut -f1,2\
 | nomer append --properties genus.properties col\
 | head
```

with genus.properties 

```
nomer.append.schema.output=[{"column":0,"type":"path.genus.id"},{"column": 1,"type":"path.genus.name"}]
```

| taxonid | taxonName | nameRelation | genusId | genusName |
| --- | --- | --- | --- | --- |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:8R493 | Cyclura |

this maps some Catalogue of Life name to it's reported genus id/name pair.

similarly, swapping out genus.properties, with order.properties:

```
| taxonid | taxonName | nameRelation | orderId | orderName |
| --- | --- | --- | --- | --- |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |
| COL:32YT6 | Cyclura lewisi | HAS_ACCEPTED_NAME | COL:45C | Squamata |

```

This maps a catalogue of life name to its reported order id/name pair.

same can be repeated for family. 

Ignoring the (possible confusing) bash scripts, do the tables look along the line of the kind of data you are looking for?

**Comment by BarbaraMeulenbelt** [comment] 2022-10-20 08:16
> Ignoring the (possible confusing) bash scripts, do the tables look along the line of the kind of data you are looking for?
Yes definitely. Does COL include EOL, GBIF etc? I did not see it in the interactions.csv

**Comment by BarbaraMeulenbelt** [comment] 2022-10-21 09:14
Is there a command in the code that I could change to acces the whole dataset?

**Comment by jhpoelen** [comment] 2022-10-25 16:49
@BarbaraMeulenbelt apologies for the delay. Still recovering from TDWG 2022. . . 

Can you please tell me what you mean by:

> Is there a command in the code that I could change to acces the whole dataset?

If you are ok installing Nomer (https://github.com/globalbioticinteractions/nomer and ok to use the Terminal, you should be able to get all the data by running by copy-pasting the following:

```
curl "https://depot.globalbioticinteractions.org/snapshot/target/data/csv/interactions.csv.gz"\
 | gunzip\
 | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName\
 | nomer replace col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"\
 > id-name-interaction-id-name.tsv
```

and then wait until it is done. This may take a while depending on your internet connection speed.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-27 10:09
Hi Jorrit! Thank you for your response. Hope you had fun at TDWG.

I installed Nomer and Miller and I managed to get the same results as you in your previous message to me. The code you gave me in your previous message only gave a small part of the dataset and I was curious how I could acces the whole dataset. That's what I meant with: 'Is there a command in the code that I could change to acces the whole dataset?' 

When I run the last code you send me I get the following:

[Screenshot 2022-10-27 at 11 29 21](https://user-images.githubusercontent.com/38956533/198247861-f3bcdaed-4e88-4875-8332-ddbfaf7f831d.png)

Do you know what this means? It does not seem to run anything anymore

> Thanks for being patient with me - I am trying to strike a balance between building re-usable tools and minimizing overhead.

Don't worry! I am very happy you can help me at all :)

**Comment by jhpoelen** [comment] 2022-10-27 13:36
@BarbaraMeulenbelt great to hear that you were able to install Nomer and miller! Yay! That makes me happy. 

Also, thanks for sharing the screenshot. 

It appears that the script is running ok, but a recent hiccup in the indexing rendered the GloBI snapshots empty. 

Perhaps best anyway to use a released version of the GloBI indexed data products via:

GloBI Community. (2022). Global Biotic Interactions: Interpreted Data Products (0.4) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.6604060

You can do that by replacing the https://depot ... link with https://zenodo.org/record/6604060/files/interactions.csv.gz .

So, the script would be:

```
curl "https://zenodo.org/record/6604060/files/interactions.csv.gz"\
 | gunzip\
 | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName\
 | nomer replace col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"\
 > id-name-interaction-id-name.tsv
```

The results will be stored in ```id-name-interaction-id-name.tsv``` . 

Oh, and if you'd like to see the results streaming in your terminal in addition to getting stored in the tsv file, you can use https://en.wikipedia.org/wiki/Tee_(command) like so:

```
curl "https://zenodo.org/record/6604060/files/interactions.csv.gz"\
 | gunzip\
 | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName\
 | nomer replace col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"\
 | tee id-name-interaction-id-name.tsv
```

Are you able to

**Comment by jhpoelen** [comment] 2022-10-27 13:41
by the way - if you'd like to write a little description of your analysis and methods (2 images + 3-4 paragraphs), I'd be happy to publish it on https://globalbioticinteractions.org/blog . I think it'd be neat to show that you can do a lot with a laptop, internet connection and some command-line tools ; )

**Comment by BarbaraMeulenbelt** [comment] 2022-10-27 16:04
Hi Jorrit! Thanks again for your elaborate answer. The code is now running in my terminal and I hope I will get the right results. I will let you know.

> by the way - if you'd like to write a little description of your analysis and methods (2 images + 3-4 paragraphs), I'd be happy to publish it on https://globalbioticinteractions.org/blog . I think it'd be neat to show that you can do a lot with a laptop, internet connection and some command-line tools ; )

Of course! Is it ok if I do this when I am a bit further in the analysis? I am planning on handing in my draft 16 december so before then I will have some results :)

**Comment by jhpoelen** [comment] 2022-10-27 18:53
@BarbaraMeulenbelt curious to see your results . . . it may take a while to process 'cause there's a bunch of information.

re: blog post - whenever you are ready. I am hoping that your work can show other how to re-use existing tools to do the kind of data magic that you are doing ; )

**Comment by BarbaraMeulenbelt** [comment] 2022-10-28 08:52
@jhpoelen I let the code running the whole night (with the nice 'caffeinate' command) in my terminal)
It seems like it suddenly gets a command to stop.

![Screenshot 2022-10-28 at 10 45 25](https://user-images.githubusercontent.com/38956533/198545661-b8e0cbdd-1ab3-4062-9768-ef64f6472fac.png)

Do you know why this is? Does it have something to do with the code or my laptop/settings?

Otherwise, the output file looks perfect, it just is small due to the premature termination.
![Screenshot 2022-10-28 at 10 49 34](https://user-images.githubusercontent.com/38956533/198546089-2caa8198-80e4-45c4-8ed9-52e37fc00027.png)

**Comment by BarbaraMeulenbelt** [comment] 2022-10-28 11:19
Thanks! I am going to let that run now and I will let you know if it works :)

Also, not neccessarily related to this issue, I have 2 questions about things I noticed. 
1: When I started working with Globi I expected only 'species' interactions results. When I printed the different ranks that were present in the dataset I was surprised. 
![image](https://user-images.githubusercontent.com/38956533/198572475-9bae02f0-761d-41c2-86e2-be757fca7d82.png)
For my thesis I am in contact with a scientist at Naturalis and I asked him till what rank I should include taxa to be relevant for my model to predict species interactions. I decided for my model that I will exclude everything above family because he told me that everything above might be too general for my model. Now I am wondering how the results of taxa with ranks like 'order', 'kingdom', 'phylum' etc. come to exist in the data. For instance a relationship between a species and a class, or between a family and a kingdom etc. Are these deduced from other interactions?

2: I printed these two columns together because I was wanted to look into 'interactsWith' as it does not tell you anything about _how_ they interact. What I saw is that the corresponding link to 'interact with' is http://purl.obolibrary.org/obo/RO_0002437 but if you click on the link it shows that this is the link for 'bioticallyInteractsWith'. 
and that 'interactsWith' has a different link, http://purl.obolibrary.org/obo/RO_0002434. Is 'bioticallyInteractWith' changed by 'interactsWith' in the csv file because it has the same meaning?

![Screenshot 2022-10-28 at 13 07 02](https://user-images.githubusercontent.com/38956533/198573105-4f09fc2d-0592-43d6-8da0-da6b3dfffe13.png)
![Screenshot 2022-10-28 at 13 08 45](https://user-images.githubusercontent.com/38956533/198573444-99da3c49-8cc4-43e5-9dbf-19c54712a23f.png)

**Comment by jhpoelen** [comment] 2022-10-28 13:54
@BarbaraMeulenbelt Thanks for asking your detailed questions with specific examples. In my experience, these are the kinds of exchanges that will help work towards better ways to share interaction data. 

You asked:
> Are these deduced from other interactions?

In my experience, the granularity of taxonomic determination depends on the datasets that was indexed, or the specific circumstance in which the interaction claim was documented. For instance, bee specialists may know that the bees they study are known to pollinate plants from a specific family, but don't care about what species from that family. So, these specialists may not bother to identify the plant below a certain taxa. Many other reasons exist why the taxonomic classification maybe at a higher taxonomic rank. Generally, the interaction claims are deduced from the actual interaction that occurred. But, the recording of these interaction observations is far from perfect.

 > Is 'bioticallyInteractWith' changed by 'interactsWith' in the csv file because it has the same meaning?

Good point! GloBI uses interactsWith to label the interaction term biotically interacts with (see https://github.com/globalbioticinteractions/globalbioticinteractions/blob/e1b7f32efbe0a686b2fd9cf97688341169e79635/eol-globi-lib/src/main/java/org/eol/globi/domain/InteractType.java#L16) . So, yes, the label should probably be changed to bioticallyInteractsWith. And, this is why I think it is important to include the term IRI (e.g., http://purl.obolibrary.org/obo/RO_0002437) along with their labels. In my mind, labels are just shorthand for the actual definitions as referenced by their IRI. Labels are for humans, IRIs are for machines.

**Comment by BarbaraMeulenbelt** [comment] 2022-10-31 12:25
Thank you for your answers, they are very informative. 
Regarding the 'interactsWith'/'bioticallyInteractsWith', isn't it still very vague what the interaction is? Is this OBO relationship given to interactions where is not clear hów they interact but it is known thát they interact?
Regarding the code, my laptop has been running all weekend, but I had to quit because I could not do anything different on my laptop because it became too slow ;)
![Screenshot 2022-10-31 at 13 07 31](https://user-images.githubusercontent.com/38956533/199006967-935ac8fe-fee5-4630-86f4-d5fbaa4eea44.png)
This is what my terminal looked like while running. Does this look how it is supposed to look?

**Comment by jhpoelen** [comment] 2022-10-31 13:10
> Regarding the 'interactsWith'/'bioticallyInteractsWith', isn't it still very vague what the interaction is? Is this OBO relationship given to interactions where is not clear hów they interact but it is known thát they interact?

Yes, interactsWith/bioticallyInteractsWith or even coOccursWith are used to document interaction claims that are either intentionally or unintentionally vague. For example, parasitologists use "ex" notation to denote the host of a parasite specimen. This "ex" can mean different things to different people: for instance, to me, a non-parasitologist, it may mean "found on", which is a weak indicator of some interaction. So, I'd translate the term "ex" to "coOccursWith", or "foundOn". But, an expert that is familiar with the collection/dataset in which the "ex" is found, may be very specific like: this parasite was parasitizing the larvea of bees in a bee nest. 

So, the short answer is: the interpretation of an interaction claim can vary depending who you talk to.

Great to hear that your laptop was running overtime. Matching millions of names can be quite computationally intense. And, yes, the screenshot you shared looks normal. Perhaps you can ask your university to get some server space to run this using ```hup``` or some other background process. Otherwise, you can rent a server somewhere (that's what I do). If all these things are a bit intimidating or not possibly somehow, please let me know an I can see if I can get you access to the GloBI server somehow.

**Comment by BarbaraMeulenbelt** [comment] 2022-11-02 14:38
> So, the short answer is: the interpretation of an interaction claim can vary depending who you talk to.

Interesting, and good to know, thanks! 
Question, if my model predicts that species X has a high chance to _coOccursWith_ species Y, based on the training data (Maybe species X _coOccursWith_ species Z and species Z _coOccursWith_ species Y, therefore species X _coOccursWith_ Y), then it is thus not always the same type of coOccursWith? Could it be that the coOccursWith between X and Y could have a different meaning than that of Y and Z? Same for the other ambiguous ones. Does that mean that when we would use a prediction like that, is it thus important to know where the prediction came from and if it is indeed valid, (looking at it with expert knowledge)? Did I interpret it right like that?

I will see what I can do with running the code. Luckily it looks ok when its running in my terminal.

**Comment by BarbaraMeulenbelt** [comment] 2022-11-07 12:46
Hi Jorrit, 

It might not be feasible to run all the data on my laptop or on a server. Is there a possibility to exclude all taxa that have a rank that is higher than 'species' while running the code? I hope this reduces the runtime.

**Comment by jhpoelen** [comment] 2022-11-07 13:27
@BarbaraMeulenbelt I propose to have a meeting to discuss. I think it is important to make sure that you get the data that you need, so that your algorithms can make the most of available knowledge. If your schedule does not allow for a meeting, I understand , and I'd be happy to continue our discussion via this github issue. Thanks for being patient: I believe your efforts will pave the way for future researchers to access existing biotic interaction data.

**Comment by jhpoelen** [comment] 2022-11-07 13:28
Please note that I am in the US Central time zone, and I can meet starting from about 15:00 NL

**Comment by BarbaraMeulenbelt** [comment] 2022-11-07 13:37
@jhpoelen Hi Jorrit, that is very nice of you to propose and take the time for. Do you mean to meet today? Would you also be willing to meet in wednesday or thursday? Any time is fine.

**Comment by jhpoelen** [comment] 2022-11-07 13:45
We can meet today if you'd like. I am available today from 15:00 - 17:00 . Otherwise Wed 15:00/16:00 NL would work. Let me know what works best for you.

**Comment by BarbaraMeulenbelt** [comment] 2022-11-07 13:53
Wednesday 15:00 is perfect for me!

**Comment by jhpoelen** [comment] 2022-11-07 13:53
Ok, please send meeting info.

**Comment by BarbaraMeulenbelt** [comment] 2022-11-07 13:57
My VU e-mail is: b.a.meulenbelt@student.vu.nl. What kind of online meeting interface do you use?

**Comment by BarbaraMeulenbelt** [comment] 2022-11-07 16:56
Thank you for the invite! me too! :)

**Comment by jhpoelen** [comment] 2022-11-10 16:55
instead of 

```
cat interactions.csv.gz\
 | gunzip\
 | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName\
 | nomer replace col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"\
 > id-name-interaction-id-name.tsv
```

you can try:

```
cat interactions.csv.gz\
 | gunzip\
 | mlr --icsv --otsvlite cut -f sourceTaxonId,sourceTaxonName,interactionTypeName,targetTaxonId,targetTaxonName\
 | nomer replace --properties replace-source.properties col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"\
 > id-name-interaction-id-name.tsv
```

where replace-source.properties something like:

```
nomer.schema.input=[{"column": 1,"type":"name"}]
nomer.schema.output=[{"column":0,"type":"externalId"},{"column": 1,"type":"name"}]
```

example:

```
echo -e "EOL:1\tHomo sapiens\tinteractsWith\tEOL:1\tHomo sapiens"\
 | nomer replace --properties replace-source.properties col 
```

yields:

```
COL:6MB3T	Homo sapiens	interactsWith	EOL:1	Homo sapiens
```


and 

```
echo -e "EOL:1\tHomo sapiens\tinteractsWith\tEOL:1\tHomo sapiens"\
 | nomer replace --properties replace-source.properties col\
 | nomer replace --properties replace-target.properties col
```

yields:

```
COL:6MB3T	Homo sapiens	interactsWith	COL:6MB3T	Homo sapiens
```

where 

replace-target.properties contains:

```
nomer.schema.input=[{"column": 4,"type":"name"}]
nomer.schema.output=[{"column":3,"type":"externalId"},{"column": 4,"type":"name"}]
```

**Comment by jhpoelen** [comment] 2022-11-10 16:58
Now, 

```
echo -e "EOL:1\tHomo sapiens\tinteractsWith\tEOL:1\tHomo sapiens"\
 | nomer replace --properties replace-source.properties col\
 | nomer replace --properties replace-target.properties col\
 | grep "COL:.*COL:.*"
```

yields:

```
COL:6MB3T	Homo sapiens	interactsWith	COL:6MB3T	Homo sapiens
```

@BarbaraMeulenbelt can you reproduce? If so, you should be able feed the entire datasets in there, instead of a single line.

**Comment by jhpoelen** [comment] 2022-12-27 23:24
@BarbaraMeulenbelt thanks for your patience in figuring out how to best use GloBI resources for your research.

Our recent exchanges suggest that you have what you need. This is why I am closing this issue. Please comments/ re-open if you feel additional items need to be addressed. 

Thanks!

**Closed by jhpoelen** 2022-12-27 23:24 UTC
