### ISSUE TITLE
Results from rGlobi vs direct data download

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#584] opened 2021-01-14 18:45 UTC
I am trying to get a count of **Apidae** records in Globi, where Apidae is the family of any taxon in either the source or target. 

Using rGlobi the results are: 84,227 
Code: https://github.com/seltmann/bee-interaction-globi/blob/master/globi-to-graph2019.R

```
#How many Apidae records are in Globi?
#pagenation, but unclear about limit of number
otherkeys = list("limit"=50000, "skip"=0)
first_page_of_ten <- get_interactions_by_taxa(sourcetaxon = "Apidae", otherkeys = otherkeys)
otherkeys = list("limit"=50000, "skip"=10000)
second_page_of_ten <- get_interactions_by_taxa(sourcetaxon = "Apidae", otherkeys = otherkeys)

#total records for Apidae is 84227
#same total if use get_interactions_by_taxa(sourcetaxon = NULL,targettaxon = "Apidae", otherkeys = otherkeys)
total <- rbind(first_page_of_ten,second_page_of_ten)

#how many rows in this dataset
nrow(total)
```

Using archived data the results are: 106,222
https://github.com/lee-michellej/globi_tritrophic_networks/blob/master/Code/Globi_bee_data.sh

```
echo Finding all Apidae
cat ../Data/interactions.tsv | grep -w "Apidae" >> ../Data/raw_globi_data/Apidae_data.tsv
wc -l ../Data/raw_globi_data/Apidae_data.tsv

echo Sorting unique records
sort -r ../Data/raw_globi_data/Apidae_data.tsv | uniq > ../Data/raw_globi_data/Apidae_data_unique.tsv
wc -l ../Data/raw_globi_data/Apidae_data_unique.tsv
```

**Comment by jhpoelen** [comment] 2021-01-19 00:22
Hi @seltmann - thanks for sharing your detailed issue.

Note that rglobi is using the globi api. This api exposes an up-to-date search index that changes often. In contrast, the published data products on Zenodo are expected to be static. 

So, when comparing rglobi search results with the Zenodo search results, differences are expected. 

Also, as noted on the https://globalbioticinteractions.org/data page, rglobi and web apis are designed for exploration and discovery. The data products shared thought Zenodo are expected to be used in final research products.

Some other details:

1. the rglobi api by default returns taxon-level interaction records. When you'd like to include individual claims (like those in interactions.tsv on Zenodo), you'll have to add the "includeObservations=true" parameters (see e.g., https://github.com/globalbioticinteractions/globalbioticinteractions/wiki/API#query-parameters). 
2. in your R example it looks like your query pages overlap: the second page should start as the end of the previous one, in your case at 50k or ```otherkeys = list("limit"=50000, "skip"=50000)```. Please see https://github.com/globalbioticinteractions/globalbioticinteractions/wiki/API#pagination for explanation of paging.
3. From your example, it is not clear where your interactions.tsv was sourced or what it's content hash was. Can you please include both location and sha256 hash to help identify the source? 

Given my comments above, your results (~100k interaction via Zenodo and ~84k via rglobi) are not that unexpected, especially given the default rglobi settings are such that interaction are summarized by sourceTaxon-interactionType-targetTaxon . 

In my experience, most rOpenSci R libraries rely on web apis. Given that web apis are inherently unstable and likely to change, I believe that they should not be used for research purposes: the requests and results returned are not versioned and make it hard to a reviewer to reproduce results or for your future self to redo your work a couple of years down the road. 

However, if you provide some more information related to your comparison after reviewing my comments and considering my suggestions, I would be happy to assist in a comparison between results obtained from rglobi vs zenodo: the more we look at the data, the better it gets!

Curious to hear your thoughts!

**Comment by seltmann** [comment] 2021-01-20 22:35
@jhpoelen Thank you for these helpful comments. For these initial explorations, we want to use the live data. This can be done through rGlobi or frequent downloads of .tsv from the live dataset. Using live data is very useful when starting a research project, especially in this case where we are also actively adding data.

One further question. When data is entered into Globi such as the interaction:

**Bee visits Plant according to Setlmann et. al.**

Does Gobi also add the reflexive even though it is not explicit in the dataset? Which would be:

**Plant is visited by Bee according to Seltmann et. al.**

**Comment by seltmann** [comment] 2021-01-20 22:42
I also am still unclear on the syntax in rGlobi to get all records that include Apidae that are listed as either the target or the source. I appreciate any suggestions.

**Comment by jhpoelen** [comment] 2021-01-20 22:57
GloBI search index includes both directions of the interactions, so searching for available Apidae interactions using either source/target taxon queries would work.

In order words, if a record reports that "a bee visits a plant", then GloBI automatically infers that "a plant was visited by a bee" .

**Comment by jhpoelen** [comment] 2021-01-20 23:00
Note that this is also the case for symmetric interaction types. So, if a claim is made that "a bee interacts with a plant", then GloBI infers that "a plant interacts with a bee".

**Comment by seltmann** [comment] 2021-01-22 17:19
@jhpoelen great! So we would then get Apidae if it is a source or a target in searching. Is the data actually indexed this way or is it a product of a sophisticated search? In other words, in the interactions.tsv file would both be found in the file?

**Comment by jhpoelen** [comment] 2021-01-22 17:58
the inferred inverse interactions are introduced into the indexes and are the result of a sophisticated search. I find it hard to distinguish between enriching an index with inferred records and sophisticated searches, because they are very much related.

By design, the interactions.tsv contains only the non-inferred, original interactions. However, I actually had to do extra work to make this happen (excluding inferred inverse interactions), so am happy to reconsider.

**Comment by seltmann** [comment] 2021-01-22 19:10
At the moment, I think it is very good that the interactions.tsv excludes inferred inverse interactions. We are still exploring the data, so I it will be a while before we have any concrete recommendations.

**Comment by jhpoelen** [comment] 2021-02-25 17:19
@seltmann thanks for the discussion re: rglobi vs interactions.tsv.gz . Closing issue for now, please feel free to re-open if needed.

**Closed by jhpoelen** 2021-02-25 17:19 UTC
