### ISSUE TITLE
Thamnophis Dietary Recodr- Update

### ISSUE THREAD

**Issue by theptin** [globalbioticinteractions/globalbioticinteractions#965] opened 2024-03-08 17:55 UTC
@theptin great to hear you are making progress! 

> Do I need to change that format in anyway, or will GloBI be able to recognize that there could be multiple prey items in a single row of the .csv?

Other datasets have similar columns, so no need to change anything at this point as far as GloBI indexing goes. 

Thanks for your update.

_Originally posted by @jhpoelen in https://github.com/globalbioticinteractions/globalbioticinteractions/issues/897#issuecomment-1539907717_
            

Hello!

I am happy to say our publication has been accepted, so our data is ready for integration into the GloBI system. The most updated version of the .csv file will live here: https://github.com/theptin/Thamnophis-GloBI/blob/main/GloBI_Thamnophis_Diet_records.csv

Is there anything else I need to do to help get the data uploaded or is that all you need?

**Comment by jhpoelen** [comment] 2024-03-08 19:43
duplicate of #897

**Closed by jhpoelen** 2024-03-08 19:43 UTC
